name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
prerelease-identifier: 'beta'
categories:
  - title: '🛠 Breaking Changes'
    labels:
      - 'breaking-change'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '👒 Dependencies and extras'
    collapse-after: 3
    labels:
      - 'chore'
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'translations'
    files:
      - '**/translations/*.json'
  - label: 'docs'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'chore'
    files:
      - '*.md'
      - '*.yml'
    branch:
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
exclude-labels:
  - 'ignore-for-release'
template: |
  ## Changes

  $CHANGES