# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.nintendo_wiiu_ristretto: debug
    python_wiiu_ristretto: debug
    aiodhcpwatcher: debug
    scapy: debug

# Enable VSCode debugging
debugpy:
  start: true
  wait: true